### ISSUE TITLE
transfers/pipeline: organization specific FTP/SFTP configuration 

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/paygate#594]
PayGate Version: `v0.9.0-dev`

With multiple organizations it becomes apparent that having different `upload.Agent` configurations for each would be really helpful. This could be accomplished by changing the configuration into an array of options. Then each organization could have a configuration option for the `id` they want to use.

```yaml
upload:
  ftpConfigs:
    - id: test
      hostname: <string>
      # ... 
  sftpConfigs:
    - id: live
      hostname: <string>
      # ... 
```

Then our `/configuration/transfers` endpoint could support the following (validated at PUT submission time):

```JSON
{
  "upload": {
    "sftpConfig": "live"
  }
}
```

This is largely a service config, which any client/UI wouldn't care about.
