### ISSUE TITLE
upload: support different configurations for organizations

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/paygate#600]
PayGate Version: `v0.9.0-dev`

With a multi-organization setup in PayGate we should support an `upload.Agent` config for each organization. This involves an array of possible configurations and then a setting on each organization for which to use.

```
upload:
  ftpConfigs:
    - id: "test" 
      hostname: <string>
      # ... 
      inboundPath: <string> # moved from ODFI config
  sftpConfigs:
    - id: "my-bank"
      hostname: <string>
      # ... 
      inboundPath: <string> # moved from ODFI config 
```

The `inboundPath`, `outboundPath`, `returnPath` configurations would need to move from `ODFI` over to each `upload.Agent` as they could be different for each server.  The [existing FTP/SFTP configs would move out from ODFI also](https://github.com/moov-io/paygate/blob/v0.9.0-dev1/pkg/config/odfi.go#L52-L53). 

This value would be stored as part of the [`organization_configuration` table we're creating](https://github.com/moov-io/paygate/issues/580). Perhaps on a column like `upload_agent_id` and a value like `sftp:my-bank`? When that value can't match to a configured ftp/sftp config we'd need to error. 

I don't think `GET/PUT /configuration/transfers` should support this value - it's internal for operators and we don't want a client changing it. If we need to support changing it in the future we can include it in the endpoint. 

This change allows `org1` to use `ftp:test` while `org2` can use `sftp:my-bank` as different upload configs. Also with https://github.com/moov-io/paygate/pull/596 we're going to be including the hostname for each server as that'll allow us to determine where files/transfers went.
